server:
  port: 0
mybatis:
  mapper-locations: classpath:mapper/*-mapper.xml
  type-aliases-package: org.millions.idea.ocr.web.finance.entity.db
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    use-generated-keys: true
    safe-row-bounds-enabled: false
    default-statement-timeout: 600
spring:
  application:
    name: mi-ocr-web-order-service
  rabbitmq:
    addresses: 121.42.187.74
    host: 121.42.187.74
    port: 5672
    username: test
    password: 123456
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 193.112.151.148
    port: 6379
    password: 123456
    timeout: 12000
    jedis:
      pool:
        max-idle: 128
        max-active: 1024
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 'x'
    url: jdbc:mysql://193.112.151.148:3306/mi-ocr-order?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: 1qQp53iydbJ709Ue
    #password: Mysql@123456
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
      virtual-host-name: mi-ocr-web-order-service
      hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
logging:
  level:
    org.millions.idea.ocr.web.captcha.agent.IUserAgentService: DEBUG
    org.millions.idea.ocr.web.captcha.agent.IWalletAgentService: DEBUG
    org.millions.idea.ocr.web.order.repository.mapper: DEBUG