server:
  port: 0
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  application:
    name: mi-ocr-web-captcha-service
  rabbitmq:
    addresses: 139.199.211.96
    host: 139.199.211.96
    port: 5672
    username: wade
    password: wade
    virtual-host: /
  redis:
    host: 47.94.107.244
    port: 6379
    password: 123456
  data:
    mongodb:
      database: mi-ocr
      host: 47.94.107.244
      port: 27017
eureka:
  instance:
      virtual-host-name: mi-ocr-web-captcha-service
      hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka