server:
  port: 20000
spring:
  application:
    name: mi-ocr-eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.85
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
    service-url:
     defaultZone: http://localhost:20000/eureka
