spring:
  profiles:
    active: dev
  application:
    name: mi-ocr-web-app


services:
  user: mi-ocr-web-user-service

---
spring:
  profiles: dev
server:
  port: 80

---
spring:
  profiles: test
server:
  port: 80