spring:
  profiles:
    active: dev
  application:
    name: mi-ocr-web-app


services:
  user: mi-ocr-web-user-service
  order: mi-ocr-web-order-service

---
spring:
  profiles: dev
server:
  port: 8088

---
spring:
  profiles: test
server:
  port: 80