server:
  port: 0
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  application:
    name: mi-ocr-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
