server:
  port: 20001
spring:
  application:
    name: mi-ocr-gateway
eureka:
  instance:
    virtual-host-name: mi-ocr-gateway
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    instance-info-replication-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 40
zuul:
  ignoredServices: '*'
  routes:
    mi-ocr-service: /ocr-api/**
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
